# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c22b2c0fb914d6f270fe752f2ae1c2cc7ac480519448ff0a8d4dff8dcff8b9e78e32e6263cb1898a935415c7516aae318630206a4e6032ad849204ff0eee3624

test:
  secret_key_base: c9a2ad6fa33d12d86d581e0fe54fd996ddd39e28781f09716c8359c75f700314b5b129e9138b534a852aea6d351d9760cf652ff61e3507a1c3365bac3eae1940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
